// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6b7adf5c-4489-430c-8bb0-773c93c897c6";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSwitch1Change();
//void onSwitch2Change();
//void onSwitch3Change();
//void onSwitch4Change();
//void onSwitch5Change();
//void onSwitch6Change();
//void onSwitch7Change();
//void onSwitch8Change();

bool switch1;
//bool switch2;
//bool switch3;
//bool switch4;
//bool switch5;
//bool switch6;
//bool switch7;
//bool switch8;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(switch1, READWRITE, ON_CHANGE, onSwitch1Change);
  //ArduinoCloud.addProperty(switch2, READWRITE, ON_CHANGE, onSwitch2Change);
  //ArduinoCloud.addProperty(switch3, READWRITE, ON_CHANGE, onSwitch3Change);
  //ArduinoCloud.addProperty(switch4, READWRITE, ON_CHANGE, onSwitch4Change);
  //ArduinoCloud.addProperty(switch5, READWRITE, ON_CHANGE, onSwitch5Change);
  //ArduinoCloud.addProperty(switch6, READWRITE, ON_CHANGE, onSwitch6Change);
  //ArduinoCloud.addProperty(switch7, READWRITE, ON_CHANGE, onSwitch7Change);
  //ArduinoCloud.addProperty(switch8, READWRITE, ON_CHANGE, onSwitch8Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
